name: Publish to NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AppStoreServerApi

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Pack
        run: dotnet pack --no-build -c Release -o nupkg /p:VersionSuffix=${{ github.run_number }}

      - name: Publish to NuGet
        run: dotnet nuget push "nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}